export const styles = {
  settingsContainer: {
    padding: "100px 20px 40px 20px",
    maxWidth: "1100px",
    margin: "0 auto",
  },
  settingsCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    marginBottom: "30px",
  },
  settingsHeader: {
    padding: "30px",
    background: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
    color: "white",
  },
  settingsHeaderH2: {
    margin: "0 0 8px 0",
    fontSize: "24px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  settingsHeaderP: {
    margin: "0",
    opacity: "0.8",
    fontSize: "14px",
  },
  settingsContent: {
    padding: "30px",
  },
  settingsSection: {
    marginBottom: "20px",
  },
  settingsSectionH3: {
    margin: "0 0 20px 0",
    fontSize: "15px",
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
  },
  scheduleSection: {
    padding: "25px",
    background: "#f8fafc",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
  },
  settingItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
    paddingBottom: "20px",
    borderBottom: "1px solid #f1f5f9",
  },
  settingItemLast: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
  },
  settingLabel: {
    flex: "1",
  },
  settingLabelLabel: {
    display: "block",
    margin: "0 0 4px 0",
    fontWeight: "600",
    color: "#1e293b",
    fontSize: "14px",
  },
  settingDescription: {
    display: "block",
    color: "#64748b",
    fontSize: "13px",
  },
  settingControl: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  checkboxInput: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  toggleIndicator: {
    padding: "4px 10px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "700",
    background: "#f1f5f9",
    color: "#64748b",
  },
  toggleIndicatorActive: {
    background: "#dcfce7",
    color: "#166534",
  },
  selectInput: {
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    minWidth: "160px",
  },
  numberInput: {
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    width: "70px",
    textAlign: "center",
  },
  scheduleSummary: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "15px",
    background: "#f0f9ff",
    borderRadius: "8px",
    color: "#0c4a6e",
    fontSize: "13px",
    border: "1px solid #bae6fd",
    marginTop: "10px",
  },
  scheduleSummaryIcon: {
    color: "#0284c7",
  },
  settingsFooter: {
    padding: "20px 30px",
    background: "#f8fafc",
    display: "flex",
    justifyContent: "flex-end",
    borderTop: "1px solid #e2e8f0",
  },
  buttonSave: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    background: "#1e293b",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  buttonSaveHover: {
    background: "#334155",
  },
  buttonSaveDisabled: {
    opacity: "0.5",
    cursor: "not-allowed",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "20px",
    marginBottom: "25px",
  },
  summaryCard: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    display: "flex",
    alignItems: "center",
    gap: "15px",
    border: "1px solid #f1f5f9",
  },
  summaryIconContainer: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    background: "#f8fafc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
  },
  summaryContent: {
    display: "flex",
    flexDirection: "column",
  },
  summaryLabel: {
    fontSize: "12px",
    color: "#64748b",
    fontWeight: "500",
  },
  summaryValue: {
    fontSize: "18px",
    color: "#1e293b",
    fontWeight: "700",
  },
  periodBadge: {
    background: "#f0f9ff",
    border: "1px solid #bae6fd",
    padding: "12px 20px",
    borderRadius: "8px",
    marginBottom: "20px",
    color: "#0369a1",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  timelineCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    overflow: "hidden",
    border: "1px solid #f1f5f9",
  },
  timelineHeader: {
    padding: "20px 25px",
    borderBottom: "1px solid #f1f5f9",
  },
  filterSection: {
    padding: "15px 25px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
  },
  filterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "15px",
    alignItems: "flex-end",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  label: {
    fontSize: "11px",
    fontWeight: "600",
    color: "#64748b",
  },
  input: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
  },
  select: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
    background: "white",
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  btnApply: {
    padding: "8px 16px",
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  btnClear: {
    padding: "8px 12px",
    background: "#e2e8f0",
    color: "#475569",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "15px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "700",
    borderBottom: "2px solid #f1f5f9",
  },
  td: {
    padding: "15px",
    color: "#334155",
    fontSize: "13px",
    borderBottom: "1px solid #f1f5f9",
  },
  tdEmpty: {
    textAlign: "center",
    padding: "40px",
    color: "#94a3b8",
  },
  tr: {
    transition: "background 0.2s",
    "&:hover": { background: "#f8fafc" },
  },
  statusSuccess: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#ecfdf5",
    color: "#059669",
    fontSize: "11px",
    fontWeight: "700",
  },
  statusError: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "11px",
    fontWeight: "700",
  },
  paginationContainer: {
    padding: "20px 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paginationInfo: {
    fontSize: "12px",
    color: "#64748b",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  pageButton: {
    padding: "6px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    background: "white",
    fontSize: "12px",
    cursor: "pointer",
  },
  pageInfo: {
    fontSize: "12px",
    color: "#1e293b",
    fontWeight: "700",
  },
  settingsLoading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "300px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
};

export const spinnerStyles = `
  @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
`;

export const mergeStyles = (...objs) => Object.assign({}, ...objs);
