export const styles = {
  settingsContainer: {
    padding: "100px 20px 40px 20px",
    maxWidth: "1100px",
    margin: "0 auto",
  },
  settingsCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    marginBottom: "30px",
  },
  settingsHeader: {
    padding: "30px",
    background: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
    color: "white",
  },
  settingsHeaderH2: {
    margin: "0 0 8px 0",
    fontSize: "24px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  settingsHeaderP: {
    margin: "0",
    opacity: "0.8",
    fontSize: "14px",
  },
  settingsContent: {
    padding: "30px",
  },
  settingsSection: {
    marginBottom: "20px",
  },
  settingsSectionH3: {
    margin: "0 0 20px 0",
    fontSize: "15px",
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
  },
  scheduleSection: {
    padding: "25px",
    background: "#f8fafc",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
  },
  settingItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
    paddingBottom: "20px",
    borderBottom: "1px solid #f1f5f9",
  },
  settingItemLast: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
  },
  settingLabel: {
    flex: "1",
  },
  settingLabelLabel: {
    display: "block",
    margin: "0 0 4px 0",
    fontWeight: "600",
    color: "#1e293b",
    fontSize: "14px",
  },
  settingDescription: {
    display: "block",
    color: "#64748b",
    fontSize: "13px",
  },
  settingControl: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    justifyContent: "flex-start",
  },
  checkboxInput: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  toggleIndicator: {
    padding: "4px 10px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "700",
    background: "#f1f5f9",
    color: "#64748b",
  },
  toggleIndicatorActive: {
    background: "#dcfce7",
    color: "#166534",
  },
  selectInput: {
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    minWidth: "160px",
  },
  numberInput: {
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    width: "70px",
    textAlign: "center",
  },
  scheduleSummary: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "15px",
    background: "#f0f9ff",
    borderRadius: "8px",
    color: "#0c4a6e",
    fontSize: "13px",
    border: "1px solid #bae6fd",
    marginTop: "10px",
  },
  scheduleSummaryIcon: {
    color: "#0284c7",
  },
  settingsFooter: {
    padding: "20px 30px",
    background: "#f8fafc",
    display: "flex",
    justifyContent: "flex-end",
    borderTop: "1px solid #e2e8f0",
  },
  buttonSave: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    background: "#1e293b",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  buttonSaveHover: {
    background: "#334155",
  },
  buttonSaveDisabled: {
    opacity: "0.5",
    cursor: "not-allowed",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "20px",
    marginBottom: "25px",
  },
  summaryCard: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    display: "flex",
    alignItems: "center",
    gap: "15px",
    border: "1px solid #f1f5f9",
  },
  summaryIconContainer: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    background: "#f8fafc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
  },
  summaryContent: {
    display: "flex",
    flexDirection: "column",
  },
  summaryLabel: {
    fontSize: "12px",
    color: "#64748b",
    fontWeight: "500",
  },
  summaryValue: {
    fontSize: "18px",
    color: "#1e293b",
    fontWeight: "700",
  },
  periodBadge: {
    background: "#f0f9ff",
    border: "1px solid #bae6fd",
    padding: "12px 20px",
    borderRadius: "8px",
    marginBottom: "20px",
    color: "#0369a1",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  timelineCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    overflow: "hidden",
    border: "1px solid #f1f5f9",
  },
  timelineHeader: {
    padding: "20px 25px",
    borderBottom: "1px solid #f1f5f9",
  },
  filterSection: {
    padding: "15px 25px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
  },
  filterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "15px",
    alignItems: "flex-end",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  label: {
    fontSize: "11px",
    fontWeight: "600",
    color: "#64748b",
  },
  input: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
  },
  select: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
    background: "white",
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  btnApply: {
    padding: "8px 16px",
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  btnClear: {
    padding: "8px 12px",
    background: "#e2e8f0",
    color: "#475569",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "15px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "700",
    borderBottom: "2px solid #f1f5f9",
  },
  td: {
    padding: "15px",
    color: "#334155",
    fontSize: "13px",
    borderBottom: "1px solid #f1f5f9",
  },
  tdEmpty: {
    textAlign: "center",
    padding: "40px",
    color: "#94a3b8",
  },
  tr: {
    transition: "background 0.2s",
    "&:hover": { background: "#f8fafc" },
  },
  statusSuccess: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#ecfdf5",
    color: "#059669",
    fontSize: "11px",
    fontWeight: "700",
  },
  statusError: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "11px",
    fontWeight: "700",
  },
  paginationContainer: {
    padding: "20px 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paginationInfo: {
    fontSize: "12px",
    color: "#64748b",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  pageButton: {
    padding: "6px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    background: "white",
    fontSize: "12px",
    cursor: "pointer",
  },
  pageInfo: {
    fontSize: "12px",
    color: "#1e293b",
    fontWeight: "700",
  },
  settingsLoading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "300px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  textInput: {
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    minWidth: "300px",
    fontFamily: "inherit",
  },
  selectPostButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    background: "#6366f1",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  selectPostButtonHover: {
    background: "#4f46e5",
  },
  selectedPostContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 16px",
    background: "#f0f9ff",
    border: "1px solid #bae6fd",
    borderRadius: "8px",
  },
  selectedPostTitle: {
    margin: "0",
    fontSize: "14px",
    fontWeight: "500",
    color: "#0369a1",
  },
  removePostButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    background: "#fee2e2",
    color: "#dc2626",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontSize: "16px",
  },
  removePostButtonHover: {
    background: "#fecaca",
  },
  tableLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(255, 255, 255, 0.7)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    borderRadius: "0 0 8px 8px",
    backdropFilter: "blur(2px)",
  },
  miniSpinner: {
    width: "32px",
    height: "32px",
    border: "3px solid #f3f3f3",
    borderTop: "3px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "10px",
  },
  actionButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 12px",
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  actionButtonHover: {
    background: "#2563eb",
    boxShadow: "0 2px 8px rgba(59, 130, 246, 0.3)",
  },
  metricsCell: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "600",
    fontSize: "13px",
  },
  warningCard: {
    background: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
    border: "2px solid #f59e0b",
    borderRadius: "8px",
    padding: "20px",
    marginTop: "20px",
    marginBottom: "30px",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.15)",
    transition: "all 0.3s ease",
  },
  warningHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "16px",
  },
  warningIcon: {
    fontSize: "24px",
    color: "#f59e0b",
  },
  warningTitle: {
    margin: 0,
    fontSize: "16px",
    color: "#92400e",
    fontWeight: "700",
  },
  warningContent: {
    color: "#78350f",
  },
  warningText: {
    margin: "8px 0",
    fontSize: "14px",
    lineHeight: "1.6",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  highlightDate: {
    background: "rgba(245, 158, 11, 0.2)",
    padding: "4px 8px",
    borderRadius: "4px",
    fontWeight: "600",
    color: "#b45309",
  },
  warningBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "#dbeafe",
    color: "#1e40af",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    marginBottom: "12px",
    marginTop: "8px",
  },
  warningDescription: {
    margin: "12px 0",
    fontSize: "13px",
    lineHeight: "1.6",
    color: "#92400e",
  },
  warningInfoBox: {
    display: "flex",
    gap: "12px",
    background: "rgba(255, 255, 255, 0.6)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    borderRadius: "6px",
    padding: "12px",
    margin: "16px 0",
    fontSize: "12px",
    lineHeight: "1.6",
    color: "#78350f",
  },
  warningInfoIcon: {
    color: "#f59e0b",
    fontSize: "16px",
    flexShrink: 0,
    marginTop: "2px",
  },
  confirmationBox: {
    background: "rgba(239, 68, 68, 0.05)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    borderRadius: "6px",
    padding: "12px",
    marginTop: "12px",
  },
  confirmationText: {
    margin: "0 0 12px 0",
    fontSize: "13px",
    color: "#7f1d1d",
    fontWeight: "600",
  },
  confirmationButtons: {
    display: "flex",
    gap: "8px",
  },
  btnClearExecution: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    background: "#f59e0b",
    color: "#fff",
    border: "none",
    padding: "10px 16px",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    marginTop: "12px",
  },
  btnConfirmClear: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "#ef4444",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    flex: 1,
  },
  btnCancelClear: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    flex: 1,
  },
  btnDisabled: {
    opacity: "0.6 !important",
    cursor: "not-allowed !important",
    pointerEvents: "none !important",
  },

  // Manual Send Button
  manualSendButtonContainer: {
    marginBottom: "30px",
    display: "flex",
    gap: "12px",
  },
  buttonManualSend: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    background: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 6px -1px rgba(245, 158, 11, 0.3)",
  },
  buttonManualSendHover: {
    background: "linear-gradient(135deg, #d97706 0%, #b45309 100%)",
    boxShadow: "0 6px 12px -1px rgba(245, 158, 11, 0.4)",
    transform: "translateY(-2px)",
  },
  buttonManualSendDisabled: {
    opacity: "0.6",
    cursor: "not-allowed",
    pointerEvents: "none",
  },

  // Modal Styles
  modalOverlay: {
    position: "fixed",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: "9999",
  },
  modal: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.15)",
    width: "90%",
    maxWidth: "500px",
    animation: "slideIn 0.3s ease",
  },
  modalHeader: {
    padding: "24px",
    background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    color: "white",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopLeftRadius: "12px",
    borderTopRightRadius: "12px",
  },
  modalTitle: {
    margin: "0",
    fontSize: "18px",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  modalCloseBtn: {
    background: "none",
    border: "none",
    color: "white",
    fontSize: "24px",
    cursor: "pointer",
    padding: "0",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "background 0.2s ease",
  },
  modalContent: {
    padding: "24px",
    borderBottom: "1px solid #e5e7eb",
  },
  modalMessage: {
    margin: "0 0 12px 0",
    fontSize: "14px",
    color: "#1e293b",
    lineHeight: "1.5",
  },
  modalSubMessage: {
    margin: "0 0 20px 0",
    fontSize: "13px",
    color: "#64748b",
    lineHeight: "1.5",
    fontStyle: "italic",
  },
  modalCheckbox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px",
    background: "#f8fafc",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  checkboxLabel: {
    margin: "0",
    fontSize: "14px",
    color: "#1e293b",
    cursor: "pointer",
    fontWeight: "500",
  },
  modalFooter: {
    padding: "16px 24px",
    display: "flex",
    gap: "12px",
    justifyContent: "flex-end",
  },
  buttonCancel: {
    padding: "10px 20px",
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  buttonConfirmSend: {
    padding: "10px 20px",
    background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  buttonConfirmSendDisabled: {
    opacity: "0.5",
    cursor: "not-allowed",
    pointerEvents: "none",
  },
};

export const spinnerStyles = `
  @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
  @keyframes slideIn {
    from {
      transform: translateY(-30px);
      opacity: 0;
    }
    to {
      transform: translateY(0);
      opacity: 1;
    }
  }
`;

export const mergeStyles = (...objs) => Object.assign({}, ...objs);
