export const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modal: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.2)",
    width: "95%",
    maxWidth: "1000px",
    height: "80vh",
    maxHeight: "800px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "24px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
    color: "white",
  },
  title: {
    margin: 0,
    fontSize: "22px",
    fontWeight: 700,
    color: "black",
  },
  closeButton: {
    background: "rgba(255,255,255,0.1)",
    border: "none",
    fontSize: "24px",
    color: "white",
    cursor: "pointer",
    padding: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "40px",
    height: "40px",
    borderRadius: "8px",
    transition: "all 0.2s ease",
  },
  closeButtonHover: {
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  searchContainer: {
    padding: "16px 24px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "white",
  },
  searchInput: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    transition: "border-color 0.2s ease",
  },
  contentWrapper: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
    backgroundColor: "white",
  },
  leftPanel: {
    width: "50%",
    borderRight: "1px solid #e2e8f0",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  rightPanel: {
    width: "50%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#f8fafc",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#64748b",
    flex: 1,
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "3px solid #e2e8f0",
    borderTop: "3px solid #6366f1",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  postsList: {
    display: "flex",
    flexDirection: "column",
    gap: "0",
    flex: 1,
  },
  postItem: {
    display: "flex",
    gap: "12px",
    padding: "14px 16px",
    borderBottom: "1px solid #e2e8f0",
    cursor: "pointer",
    transition: "all 0.2s ease",
    backgroundColor: "white",
  },
  postItemActive: {
    backgroundColor: "#e0e7ff",
    borderLeftColor: "#6366f1",
    borderLeft: "4px solid #6366f1",
  },
  postImage: {
    width: "70px",
    height: "70px",
    borderRadius: "6px",
    objectFit: "cover",
    flexShrink: 0,
  },
  postItemContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "4px",
  },
  postItemTitle: {
    margin: "0",
    fontSize: "13px",
    fontWeight: 600,
    color: "#1e293b",
    lineHeight: "1.3",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  },
  postItemDate: {
    margin: "0",
    fontSize: "11px",
    color: "#94a3b8",
  },
  emptyContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#94a3b8",
    flex: 1,
  },
  emptyIcon: {
    fontSize: "48px",
    marginBottom: "12px",
    opacity: 0.4,
  },
  emptyText: {
    margin: "0",
    fontSize: "14px",
    fontWeight: 500,
  },
  previewContainer: {
    padding: "24px",
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  previewTitle: {
    margin: "0 0 16px 0",
    fontSize: "14px",
    fontWeight: 700,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  previewImage: {
    width: "100%",
    height: "180px",
    borderRadius: "8px",
    objectFit: "cover",
    marginBottom: "16px",
  },
  previewPostTitle: {
    margin: "0 0 8px 0",
    fontSize: "16px",
    fontWeight: 700,
    color: "#1e293b",
    lineHeight: "1.4",
  },
  previewPostDate: {
    margin: "0 0 12px 0",
    fontSize: "12px",
    color: "#94a3b8",
  },
  previewPostDescription: {
    margin: "0 0 16px 0",
    fontSize: "13px",
    color: "#64748b",
    lineHeight: "1.6",
  },
  selectButton: {
    padding: "12px 18px",
    background: "#1e293b",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.2s ease",
    marginTop: "auto",
  },
  paginationPlaceholder: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    color: "#94a3b8",
    textAlign: "center",
  },
  paginationContainerBottom: {
    padding: "16px 24px",
    borderTop: "1px solid #e2e8f0",
    backgroundColor: "white",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paginationInfo: {
    fontSize: "13px",
    color: "#64748b",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  paginationButtons: {
    display: "flex",
    gap: "8px",
  },
  paginationButton: {
    padding: "8px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    backgroundColor: "white",
    color: "#1e293b",
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  paginationButtonHover: {
    backgroundColor: "#f1f5f9",
    borderColor: "#94a3b8",
  },
  paginationButtonDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
};

// Add CSS animation for spinner
if (typeof document !== "undefined") {
  const styleSheet = document.createElement("style");
  styleSheet.textContent = `
    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  `;
  document.head.appendChild(styleSheet);
}
