const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: "16px",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2)",
    width: "100%",
    maxWidth: "700px",
    maxHeight: "90vh",
    overflow: "auto",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #e5e7eb",
    position: "sticky",
    top: 0,
    backgroundColor: "#ffffff",
    zIndex: 100,
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#1f2937",
    margin: 0,
  },
  closeButton: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#6b7280",
    padding: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "all 0.2s ease",
  },
  form: {
    padding: "20px",
  },
  formGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "14px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    transition: "all 0.2s ease",
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "14px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    resize: "vertical",
    transition: "all 0.2s ease",
  },
  errorMessage: {
    padding: "12px 16px",
    margin: "16px 20px 0 20px",
    backgroundColor: "#fee2e2",
    color: "#991b1b",
    borderRadius: "6px",
    fontSize: "14px",
    border: "1px solid #fca5a5",
  },
  questionsSection: {
    marginTop: "30px",
    paddingTop: "20px",
    borderTop: "1px solid #e5e7eb",
  },
  questionsTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "16px",
  },
  questionsList: {
    backgroundColor: "#f9fafb",
    borderRadius: "6px",
    padding: "12px",
    marginBottom: "20px",
    maxHeight: "300px",
    overflowY: "auto",
  },
  questionItem: {
    backgroundColor: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    padding: "12px",
    marginBottom: "8px",
    fontSize: "13px",
  },
  questionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "6px",
  },
  questionNumber: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    backgroundColor: "#3b82f6",
    color: "white",
    borderRadius: "50%",
    fontSize: "12px",
    fontWeight: "600",
    flexShrink: 0,
  },
  questionText: {
    flex: 1,
    color: "#374151",
    fontWeight: "500",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  removeQuestionBtn: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#ef4444",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    flexShrink: 0,
  },
  questionDetails: {
    color: "#6b7280",
    fontSize: "12px",
    marginLeft: "32px",
  },
  addQuestionSection: {
    backgroundColor: "#f0f9ff",
    border: "1px solid #bfdbfe",
    borderRadius: "6px",
    padding: "16px",
    marginTop: "16px",
  },
  addQuestionTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#1e40af",
    marginBottom: "12px",
    marginTop: 0,
  },
  alternativesSection: {
    marginBottom: "16px",
  },
  alternativeInput: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  alternativeLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    minWidth: "24px",
  },
  alternativeTextInput: {
    flex: 1,
    padding: "8px 10px",
    fontSize: "13px",
    border: "1px solid #d1d5db",
    borderRadius: "4px",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  removeAltBtn: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#ef4444",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
  },
  addAltBtn: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "8px 10px",
    backgroundColor: "#eff6ff",
    color: "#0284c7",
    border: "1px solid #bae6fd",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s ease",
    marginTop: "8px",
  },
  addQuestionBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: "10px",
    backgroundColor: "#dbeafe",
    color: "#0c4a6e",
    border: "1px solid #7dd3fc",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  formActions: {
    display: "flex",
    gap: "12px",
    marginTop: "30px",
    paddingTop: "20px",
    borderTop: "1px solid #e5e7eb",
  },
  cancelButton: {
    flex: 1,
    padding: "10px 16px",
    backgroundColor: "#f3f4f6",
    color: "#374151",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  submitButton: {
    flex: 1,
    padding: "10px 16px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
};

export default styles;
