const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: "16px",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2)",
    width: "100%",
    maxHeight: "90vh",
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "20px",
    borderBottom: "1px solid #e5e7eb",
    position: "sticky",
    top: 0,
    backgroundColor: "#ffffff",
    zIndex: 100,
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#1f2937",
    margin: "0 0 4px 0",
  },
  modalSubtitle: {
    fontSize: "13px",
    color: "#6b7280",
    margin: "0",
  },
  closeButton: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#6b7280",
    padding: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "all 0.2s ease",
  },
  filterSection: {
    padding: "12px 20px",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  filterSelect: {
    padding: "8px 12px",
    fontSize: "14px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    color: "#374151",
    cursor: "pointer",
    fontFamily: "inherit",
    backgroundColor: "#ffffff",
  },
  errorMessage: {
    padding: "12px 16px",
    margin: "16px 20px 0 20px",
    backgroundColor: "#fee2e2",
    color: "#991b1b",
    borderRadius: "6px",
    fontSize: "14px",
    border: "1px solid #fca5a5",
  },
  responsesContainer: {
    flex: 1,
    overflow: "auto",
    padding: "20px",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#6b7280",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #e5e7eb",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  responsesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  responseCard: {
    backgroundColor: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "16px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  responseCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
  },
  responseCardInfo: {
    flex: 1,
  },
  responseCardName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#1f2937",
    margin: "0 0 4px 0",
  },
  responseCardEmail: {
    fontSize: "13px",
    color: "#6b7280",
    margin: "0 0 2px 0",
  },
  responseCardPhone: {
    fontSize: "13px",
    color: "#6b7280",
    margin: "0",
  },
  responseCardMeta: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "6px",
  },
  contactBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "600",
    whiteSpace: "nowrap",
  },
  responseDate: {
    fontSize: "12px",
    color: "#6b7280",
  },
  responseCardFooter: {
    marginTop: "12px",
    paddingTop: "12px",
    borderTop: "1px solid #f3f4f6",
  },
  clickHint: {
    color: "#9ca3af",
    fontSize: "12px",
  },
  emptyState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "200px",
    color: "#6b7280",
    fontSize: "14px",
  },
  detailHeader: {
    padding: "20px",
    borderBottom: "1px solid #e5e7eb",
    position: "sticky",
    top: 0,
    backgroundColor: "#ffffff",
    zIndex: 100,
  },
  backButton: {
    backgroundColor: "transparent",
    border: "none",
    color: "#3b82f6",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    padding: "0",
    marginBottom: "12px",
    transition: "color 0.2s ease",
  },
  detailTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
    margin: "0 0 4px 0",
  },
  detailSubtitle: {
    fontSize: "13px",
    color: "#6b7280",
    margin: "0",
  },
  detailContent: {
    flex: 1,
    overflow: "auto",
    padding: "20px",
  },
  detailSection: {
    marginBottom: "20px",
  },
  detailLabel: {
    display: "block",
    fontSize: "12px",
    fontWeight: "600",
    color: "#6b7280",
    textTransform: "uppercase",
    marginBottom: "6px",
  },
  detailValue: {
    fontSize: "14px",
    color: "#1f2937",
    margin: "0",
  },
  observationsTextarea: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "13px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    resize: "vertical",
  },
  jsonDisplay: {
    backgroundColor: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "11px",
    overflow: "auto",
    maxHeight: "200px",
    fontFamily: "monospace",
    color: "#1f2937",
    margin: "0",
  },
  detailActions: {
    display: "flex",
    gap: "12px",
    padding: "20px",
    borderTop: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  cancelButton: {
    padding: "10px 16px",
    backgroundColor: "#f3f4f6",
    color: "#374151",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  contactButton: {
    padding: "10px 16px",
    backgroundColor: "#fbbf24",
    color: "#78350f",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  saveButton: {
    padding: "10px 16px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
};

export default styles;
