const styles = {
  container: {
    width: "100%",
  },
  headerSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
    flexWrap: "wrap",
    gap: "20px",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#1f2937",
    margin: "0 0 8px 0",
  },
  sectionSubtitle: {
    fontSize: "14px",
    color: "#6b7280",
    margin: "0",
  },
  createButton: {
    display: "flex",
    alignItems: "center",
    padding: "10px 16px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: "#2563eb",
    },
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    color: "#6b7280",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #e5e7eb",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  tableWrapper: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    overflow: "x-auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  tableHeader: {
    backgroundColor: "#f9fafb",
    borderBottom: "1px solid #e5e7eb",
  },
  thId: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    width: "80px",
  },
  thStatus: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    width: "100px",
  },
  thName: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    minWidth: "150px",
  },
  thDescription: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    minWidth: "200px",
  },
  thDate: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    minWidth: "150px",
  },
  thActions: {
    padding: "12px 16px",
    textAlign: "center",
    fontWeight: "600",
    color: "#6b7280",
    fontSize: "12px",
    textTransform: "uppercase",
    minWidth: "150px",
  },
  tableRow: {
    borderBottom: "1px solid #e5e7eb",
    transition: "background-color 0.2s ease",
    "&:hover": {
      backgroundColor: "#f9fafb",
    },
  },
  tdId: {
    padding: "12px 16px",
  },
  tdStatus: {
    padding: "12px 16px",
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    fontSize: "13px",
    fontWeight: "500",
    color: "#374151",
  },
  tdName: {
    padding: "12px 16px",
    fontWeight: "500",
    color: "#1f2937",
  },
  tdDescription: {
    padding: "12px 16px",
    color: "#6b7280",
    maxWidth: "300px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tdDate: {
    padding: "12px 16px",
    color: "#6b7280",
    fontSize: "13px",
  },
  tdActions: {
    padding: "12px 16px",
    display: "flex",
    gap: "8px",
    justifyContent: "center",
  },
  actionButton: {
    padding: "6px 8px",
    backgroundColor: "transparent",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    color: "#6b7280",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    "&:hover": {
      backgroundColor: "#f3f4f6",
      borderColor: "#9ca3af",
      color: "#374151",
    },
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    color: "#6b7280",
  },
  emptyIcon: {
    fontSize: "48px",
    color: "#d1d5db",
    marginBottom: "16px",
  },
  emptyTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  emptyText: {
    fontSize: "14px",
    color: "#6b7280",
    marginBottom: "20px",
  },
  createButtonEmpty: {
    padding: "10px 16px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
};

export default styles;
