const colors = {
  primary: "#3B82F6",
  primaryHover: "#2563EB",
  secondary: "#64748B",
  textMain: "#1E293B",
  backgroundOverlay: "rgba(15, 23, 42, 0.6)",
  white: "#FFFFFF",
  bgLight: "#F8FAFC",
  border: "#E2E8F0",
  success: "#10B981",
  successBg: "#ECFDF5",
  danger: "#EF4444",
  dangerBg: "#FEF2F2",
  warning: "#F59E0B",
  customBg: "#EFF6FF",
  customBorder: "#3B82F6",
  retroBg: "#FFF7ED",
  retroBorder: "#FFEDD5",
  retroText: "#9A3412",
};

const styles = {
  modalContainer: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1000,
    background: colors.backgroundOverlay,
    backdropFilter: "blur(4px)",
    padding: 20,
    boxSizing: "border-box",
    animation: "fadeIn 0.2s ease-out",
  },
  modalBody: {
    width: "100%",
    maxWidth: 550,
    background: colors.white,
    borderRadius: 16,
    boxShadow:
      "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    maxHeight: "90vh",
    overflow: "hidden",
    position: "relative",
  },
  modalHeader: {
    padding: "20px 24px",
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: colors.white,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.textMain,
    margin: 0,
  },
  closeButton: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 8,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.secondary,
    transition: "all 0.2s",
  },
  modalContent: {
    padding: "24px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  inputGroup: {
    display: "flex",
    gap: 12,
    width: "100%",
  },
  inputField: {
    flexGrow: 1,
    padding: "12px 16px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.bgLight,
    fontSize: 15,
    color: colors.textMain,
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  searchButton: {
    padding: "0 24px",
    borderRadius: 8,
    border: "none",
    backgroundColor: colors.primary,
    color: colors.white,
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  resultsContainer: {
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    overflow: "hidden",
    marginTop: 10,
  },
  listHeader: {
    display: "block",
    padding: "10px 16px",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: colors.secondary,
    backgroundColor: colors.bgLight,
    fontWeight: "600",
    borderBottom: `1px solid ${colors.border}`,
  },
  listItem: {
    padding: "12px 16px",
    cursor: "pointer",
    fontSize: 15,
    color: colors.textMain,
    borderBottom: `1px solid ${colors.border}`,
    transition: "background-color 0.15s",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectedCard: {
    marginTop: 10,
    padding: 20,
    borderRadius: 12,
    backgroundColor: colors.successBg,
    border: `1px solid ${colors.success}40`,
    display: "flex",
    flexDirection: "column",
    gap: 15,
    alignItems: "center",
    textAlign: "center",
  },
  selectedText: {
    fontSize: 16,
    color: "#065F46",
  },
  configHeaderRow: {
    display: "flex",
    alignItems: "center",
    marginBottom: 10,
  },
  backLink: {
    background: "none",
    border: "none",
    color: colors.secondary,
    cursor: "pointer",
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    padding: 0,
    marginRight: 15,
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.secondary,
  },
  currencyWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  currencySymbol: {
    position: "absolute",
    left: 16,
    color: colors.secondary,
    fontWeight: "500",
  },
  inputCurrency: {
    width: "100%",
    padding: "12px 16px 12px 40px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.bgLight,
    fontSize: 16,
    color: colors.textMain,
    outline: "none",
  },
  selectField: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.bgLight,
    fontSize: 15,
    color: colors.textMain,
    outline: "none",
    cursor: "pointer",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "center",
    padding: "12px 16px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  checkbox: {
    width: 18,
    height: 18,
    marginRight: 12,
    accentColor: colors.primary,
    cursor: "pointer",
  },
  checkboxLabel: {
    fontSize: 15,
    color: colors.textMain,
    cursor: "pointer",
  },
  simulationBox: {
    backgroundColor: "#EFF6FF",
    border: `1px solid ${colors.primary}30`,
    borderRadius: 10,
    padding: 16,
    marginTop: 10,
  },
  simRow: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 8,
    fontSize: 14,
    color: colors.secondary,
  },
  simValue: {
    fontWeight: "700",
    color: colors.primary,
    fontSize: 16,
  },
  actionButtons: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 20,
  },
  btnPrimary: {
    width: "100%",
    padding: "14px",
    borderRadius: 10,
    border: "none",
    backgroundColor: colors.primary,
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.2s",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btnSecondary: {
    width: "100%",
    padding: "14px",
    borderRadius: 10,
    border: `1px solid ${colors.primary}`,
    backgroundColor: "transparent",
    color: colors.primary,
    fontSize: 16,
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  errorText: {
    fontSize: 13,
    color: colors.danger,
    marginTop: 4,
  },
  customConfigBox: {
    marginTop: 10,
    padding: 15,
    backgroundColor: colors.customBg,
    borderRadius: 8,
    border: `1px solid ${colors.customBorder}`,
  },
  retroConfigBox: {
    marginTop: 10,
    padding: 15,
    backgroundColor: colors.retroBg,
    borderRadius: 8,
    border: `1px solid ${colors.retroBorder}`,
  },
};

export { styles, colors };
