const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "8px",
    width: "100%",
    maxWidth: "900px",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #eee",
    position: "sticky",
    top: 0,
    backgroundColor: "white",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: 0,
  },
  closeButton: {
    fontSize: "24px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    color: "#999",
  },
  modalBody: {
    padding: "20px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "15px",
  },
  label: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#122C4F",
  },
  input: {
    padding: "10px 12px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    width: "100%",
    transition: "all 0.2s ease",
  },
  inputDisabled: {
    backgroundColor: "#f5f5f5",
    color: "#999",
    cursor: "not-allowed",
    opacity: 0.7,
  },
  categoriesCheckbox: {
    display: "flex",
    flexWrap: "wrap",
    gap: "15px",
    padding: "10px",
    backgroundColor: "#f9f9f9",
    borderRadius: "4px",
    border: "1px solid #eee",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "13px",
    cursor: "pointer",
  },
  checkbox: {
    cursor: "pointer",
  },
  helperText: {
    fontSize: "12px",
    color: "#999",
    fontStyle: "italic",
  },
  errorText: {
    fontSize: "12px",
    color: "#dc3545",
    marginTop: "4px",
  },
  imagePreview: {
    maxWidth: "200px",
    maxHeight: "150px",
    borderRadius: "4px",
    marginTop: "10px",
    border: "1px solid #ddd",
  },
  formActions: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    paddingTop: "20px",
    borderTop: "1px solid #eee",
  },
  previewButton: {
    padding: "10px 20px",
    backgroundColor: "#17a2b8",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
  },
  submitButton: {
    padding: "10px 20px",
    backgroundColor: "#122C4F",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
  },
  submitButtonHover: {
    backgroundColor: "#0d1f3a",
    boxShadow: "0 2px 8px rgba(18, 44, 79, 0.3)",
  },
  submitButtonDisabled: {
    backgroundColor: "#122C4F",
    cursor: "not-allowed",
    opacity: 0.8,
  },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
  },
  cancelButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
};

export default styles;
