const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "8px",
    width: "100%",
    maxWidth: "600px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
    display: "flex",
    flexDirection: "column",
    maxHeight: "90vh",
    overflow: "auto",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #eee",
    position: "sticky",
    top: 0,
    backgroundColor: "white",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#dc3545",
    margin: 0,
  },
  closeButton: {
    fontSize: "24px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    color: "#999",
  },
  modalBody: {
    padding: "20px",
    flex: 1,
    overflowY: "auto",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    gap: "15px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #f0f0f0",
    borderTop: "4px solid #122C4F",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: {
    color: "#666",
    fontSize: "14px",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  warningText: {
    color: "#666",
    fontSize: "14px",
    margin: 0,
  },
  confirmText: {
    color: "#333",
    fontSize: "14px",
    fontWeight: "bold",
    margin: 0,
  },
  warningBox: {
    backgroundColor: "#fff3cd",
    border: "1px solid #ffc107",
    borderRadius: "4px",
    padding: "12px",
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
  },
  warningIcon: {
    fontSize: "18px",
    flexShrink: 0,
  },
  postsPreview: {
    backgroundColor: "#f9f9f9",
    border: "1px solid #eee",
    borderRadius: "4px",
    padding: "12px",
  },
  previewTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: "0 0 10px 0",
  },
  postsList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  postItem: {
    fontSize: "12px",
    color: "#555",
    padding: "6px 0",
    borderBottom: "1px solid #eee",
  },
  actionSelector: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  selectorTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: 0,
  },
  actionOption: {
    display: "flex",
    gap: "12px",
    padding: "12px",
    backgroundColor: "#f9f9f9",
    border: "1px solid #ddd",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  actionOptionSelected: {
    backgroundColor: "#e7f3ff",
    border: "1px solid #122C4F",
  },
  radio: {
    cursor: "pointer",
    marginTop: "3px",
    flexShrink: 0,
  },
  optionContent: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flex: 1,
  },
  optionTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: 0,
  },
  optionDescription: {
    fontSize: "12px",
    color: "#666",
    margin: 0,
  },
  categorySelect: {
    padding: "6px 8px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "12px",
    marginTop: "6px",
  },
  dangerWarning: {
    fontSize: "12px",
    color: "#dc3545",
    fontWeight: "bold",
    margin: "6px 0 0 0",
  },
  modalFooter: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    padding: "20px",
    borderTop: "1px solid #eee",
    backgroundColor: "#f9f9f9",
  },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
    transition: "all 0.2s ease",
  },
  deleteButton: {
    padding: "10px 20px",
    backgroundColor: "#dc3545",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
    transition: "all 0.2s ease",
  },
};

export default styles;
