const styles = {
  container: {
    width: "100%",
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
    gap: "20px",
  },
  headerLeft: {
    flex: 1,
    minWidth: "300px",
  },
  heading: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#122C4F",
    margin: "0 0 16px 0",
    letterSpacing: "-0.3px",
  },
  searchInput: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #e0e6ed",
    borderRadius: "8px",
    fontSize: "14px",
    boxSizing: "border-box",
    transition: "all 0.3s ease",
    backgroundColor: "#f8f9fc",
  },
  createButton: {
    padding: "12px 24px",
    backgroundColor: "#122C4F",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 12px rgba(18, 44, 79, 0.2)",
    minWidth: "160px",
    height: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  postsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
    gap: "20px",
    marginBottom: "30px",
    animation: "fadeIn 0.6s ease",
  },
  postCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
    transition: "all 0.3s ease",
    border: "1px solid #e0e6ed",
    cursor: "pointer",
    animation: "slideUp 0.5s ease",
  },
  postCardHover: {
    transform: "translateY(-4px)",
    boxShadow: "0 12px 24px rgba(0,0,0,0.12)",
  },
  postImage: {
    width: "100%",
    height: "180px",
    objectFit: "cover",
    backgroundColor: "#e0e6ed",
  },
  postImagePlaceholder: {
    width: "100%",
    height: "180px",
    backgroundColor: "#f0f3f8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    color: "#8892a0",
    fontWeight: "500",
  },
  postContent: {
    padding: "16px",
  },
  postTitle: {
    fontSize: "15px",
    fontWeight: "600",
    color: "#122C4F",
    margin: "0 0 8px 0",
    lineHeight: "1.4",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  postMeta: {
    display: "flex",
    gap: "12px",
    fontSize: "12px",
    color: "#8892a0",
    marginBottom: "12px",
    flexWrap: "wrap",
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  postExcerpt: {
    fontSize: "13px",
    color: "#666",
    margin: "0 0 12px 0",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    lineHeight: "1.4",
  },
  postFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "12px",
    borderTop: "1px solid #e0e6ed",
  },
  badge: {
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.3px",
  },
  badgeActive: {
    backgroundColor: "rgba(34, 197, 94, 0.1)",
    color: "#15803d",
  },
  badgeInactive: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    color: "#b91c1c",
  },
  actionsContainer: {
    display: "flex",
    gap: "6px",
  },
  actionButton: {
    padding: "6px 10px",
    border: "none",
    backgroundColor: "#f0f3f8",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  actionButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  deleteButton: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    color: "#dc3545",
  },
  deleteButtonDisabled: {
    opacity: 0.8,
    cursor: "not-allowed",
  },
  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "15px",
    marginTop: "30px",
    paddingTop: "30px",
    borderTop: "1px solid #e0e6ed",
  },
  paginationButton: {
    padding: "10px 16px",
    backgroundColor: "#122C4F",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  pageInfo: {
    fontSize: "14px",
    color: "#8892a0",
    fontWeight: "600",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    color: "#8892a0",
  },
  emptyIcon: {
    fontSize: "36px",
    marginBottom: "16px",
    opacity: "0.5",
    fontWeight: "300",
  },
  loadingContainer: {
    textAlign: "center",
    padding: "60px 40px",
  },
  loadingSpinner: {
    display: "inline-block",
    width: "40px",
    height: "40px",
    border: "4px solid #e0e6ed",
    borderTop: "4px solid #122C4F",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  loadingText: {
    fontSize: "15px",
    color: "#8892a0",
    fontWeight: "500",
  },
  filtersContainer: {
    display: "flex",
    gap: "16px",
    alignItems: "flex-end",
    marginBottom: "24px",
    padding: "16px",
    backgroundColor: "#f8f9fc",
    borderRadius: "8px",
    border: "1px solid #e0e6ed",
    flexWrap: "wrap",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  filterLabel: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#122C4F",
  },
  filterSelect: {
    padding: "10px 12px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    fontSize: "13px",
    backgroundColor: "white",
    cursor: "pointer",
    minWidth: "130px",
    transition: "all 0.2s ease",
  },
  filterInput: {
    padding: "10px 12px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    fontSize: "13px",
    backgroundColor: "white",
    minWidth: "140px",
    transition: "all 0.2s ease",
  },
  filterButton: {
    padding: "10px 20px",
    backgroundColor: "#17a2b8",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    marginTop: "auto",
  },
};

export default styles;
