const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "8px",
    width: "100%",
    maxWidth: "800px",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #eee",
    position: "sticky",
    top: 0,
    backgroundColor: "white",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: 0,
  },
  closeButton: {
    fontSize: "24px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    color: "#999",
  },
  modalBody: {
    padding: "20px",
  },
  heroImage: {
    width: "100%",
    maxHeight: "300px",
    objectFit: "cover",
    borderRadius: "8px",
    marginBottom: "20px",
  },
  metadata: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "12px",
    padding: "15px",
    backgroundColor: "#f9f9f9",
    borderRadius: "6px",
    marginBottom: "20px",
    fontSize: "13px",
  },
  metaItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  badge: {
    display: "inline-block",
    padding: "4px 8px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "bold",
    width: "fit-content",
  },
  badgeActive: {
    backgroundColor: "#d4edda",
    color: "#155724",
  },
  badgeInactive: {
    backgroundColor: "#f8d7da",
    color: "#721c24",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#122C4F",
    margin: "0 0 15px 0",
    lineHeight: "1.3",
  },
  excerpt: {
    fontSize: "16px",
    color: "#666",
    fontStyle: "italic",
    padding: "15px",
    backgroundColor: "#f5f5f5",
    borderLeft: "4px solid #C9A96E",
    marginBottom: "20px",
    lineHeight: "1.5",
  },
  content: {
    fontSize: "14px",
    lineHeight: "1.8",
    color: "#333",
    marginBottom: "20px",
    "& h2": {
      fontSize: "20px",
      marginTop: "20px",
      marginBottom: "10px",
    },
    "& p": {
      marginBottom: "12px",
    },
    "& strong": {
      fontWeight: "bold",
    },
    "& em": {
      fontStyle: "italic",
    },
  },
  actions: {
    paddingTop: "20px",
    borderTop: "1px solid #eee",
    textAlign: "center",
  },
  closeButtonFull: {
    padding: "10px 40px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
  },
};

export default styles;
