const styles = {
  withdrawalsPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    padding: "80px 30px 30px 30px",
    boxSizing: "border-box",
    width: "100%",
    backgroundColor: "#f8f9fa",
    minHeight: "100vh",
  },
  withdrawalsPageHeader: {
    marginBottom: "24px",
  },
  headerH1: {
    fontSize: "clamp(1.5rem, 5vw, 2.25rem)",
    fontWeight: 700,
    color: "#1a202c",
    margin: 0,
  },
  tableControlsHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "16px",
    flexWrap: "wrap",
  },
  searchBox: {
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    minWidth: "280px",
  },
  searchIcon: { color: "#9ca3af" },
  searchInput: {
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    width: "100%",
  },
  actionsGroup: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
    width: "100%",
    maxWidth: "500px",
    justifyContent: "flex-end",
  },
  filterSelect: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "12px 16px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    cursor: "pointer",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    flex: 1,
    minWidth: "150px",
  },
  createWithdrawalButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
    whiteSpace: "nowrap",
  },
  bulkActionsBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    backgroundColor: "#1f2937",
    color: "#fff",
    borderRadius: "12px",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "12px",
  },
  bulkText: {
    fontSize: "0.9rem",
    fontWeight: 500,
  },
  bulkButtonsGroup: {
    display: "flex",
    gap: "8px",
  },
  bulkActionButton: {
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    fontWeight: 600,
    color: "#fff",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  withdrawalsTableCard: {
    background: "#ffffff",
    borderRadius: "16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "clamp(8px, 2vw, 16px)",
    width: "100%",
    boxSizing: "border-box",
  },
  tableWrapper: {
    width: "100%",
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
  },
  withdrawalsTable: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "800px",
  },
  tableHeaderCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 700,
    letterSpacing: "0.05em",
  },
  tableRow: {
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  tableRowSelected: {
    backgroundColor: "rgba(59, 130, 246, 0.05)",
  },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  statusBadge: {
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "0.7rem",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
  statusAprovado: { backgroundColor: "#def7ec", color: "#03543f" },
  statusNegado: { backgroundColor: "#fee2e2", color: "#991b1b" },
  actionButtons: { display: "flex", gap: "8px" },
  actionButton: {
    border: "none",
    width: "34px",
    height: "34px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "0.9rem",
    color: "#fff",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  approveBtn: { backgroundColor: "#10b981" },
  denyBtn: { backgroundColor: "#ef4444" },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "12px",
    flexWrap: "wrap",
  },
  paginationSpan: {
    fontSize: "0.85rem",
    color: "#6b7280",
    fontWeight: 600,
  },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "10px",
    cursor: "pointer",
    transition: "all 0.2s",
    fontSize: "0.85rem",
    fontWeight: 500,
  },
  paginationButtonDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
};

export default styles;
