const styles = {
  container: {
    padding: "100px 24px 24px 24px",
    boxSizing: "border-box",
    maxWidth: "1200px",
    margin: "0 auto",
    animation: "fadeIn 0.5s ease-out",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "none",
    border: "none",
    color: "#64748b",
    cursor: "pointer",
    fontWeight: "600",
  },
  headerActions: {
    display: "flex",
    gap: "12px",
  },
  whatsappButton: {
    backgroundColor: "#22c55e",
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "600",
    cursor: "pointer",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1.5fr",
    gap: "24px",
  },
  column: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    border: "1px solid #e5e7eb",
  },
  profileHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    marginBottom: "20px",
  },
  avatar: {
    width: "70px",
    height: "70px",
    backgroundColor: "#4f46e5",
    color: "white",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "28px",
    fontWeight: "bold",
    marginBottom: "12px",
  },
  name: {
    fontSize: "20px",
    fontWeight: "700",
    color: "#1e293b",
    margin: "0 0 4px 0",
  },
  idBadge: {
    fontSize: "12px",
    color: "#94a3b8",
    fontWeight: "600",
  },
  infoList: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  infoItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "14px",
    color: "#475569",
  },
  cardTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#334155",
    marginBottom: "18px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  statusControlRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    padding: "12px",
    borderRadius: "8px",
  },
  statusInfoText: {
    display: "flex",
    flexDirection: "column",
  },
  statusLabel: {
    fontSize: "11px",
    color: "#94a3b8",
    fontWeight: "700",
  },
  statusValue: {
    fontSize: "14px",
    fontWeight: "800",
  },
  toggleButton: {
    border: "none",
    padding: "8px 12px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  contactDateBox: {
    marginTop: "12px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "#64748b",
    fontStyle: "italic",
    paddingLeft: "4px",
  },
  formGroup: {
    marginBottom: "16px",
  },
  textarea: {
    width: "100%",
    minHeight: "150px",
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    "&:focus": { borderColor: "#4f46e5" },
  },
  saveObsButton: {
    width: "100%",
    backgroundColor: "#1e293b",
    color: "white",
    border: "none",
    padding: "12px",
    borderRadius: "8px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "background 0.2s",
  },
  dataGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  dataItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  dataLayer: {
    fontSize: "11px",
    color: "#94a3b8",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  dataValue: {
    fontSize: "14px",
    color: "#1e293b",
    fontWeight: "500",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  presentationText: {
    fontSize: "14px",
    color: "#475569",
    lineHeight: "1.6",
    backgroundColor: "#f8fafc",
    padding: "16px",
    borderRadius: "8px",
    margin: 0,
  },
  checkItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
    fontSize: "14px",
    color: "#475569",
  },
  loading: {
    padding: "100px",
    textAlign: "center",
    color: "#64748b",
  },
};

export default styles;
