const styles = {
  pageContainer: {
    padding: "80px 40px",
    backgroundColor: "#f8fafc",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "30px",
  },
  backButton: {
    padding: "8px 16px",
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    color: "#64748b",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#1e293b",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "24px",
  },
  infoCard: {
    backgroundColor: "#fff",
    padding: "24px",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  editCard: {
    backgroundColor: "#fff",
    padding: "24px",
    borderRadius: "12px",
    border: "2px solid #6366f1",
    boxShadow: "0 4px 6px -1px rgba(99, 102, 241, 0.1)",
  },
  cardTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#334155",
    marginBottom: "20px",
    borderBottom: "1px solid #f1f5f9",
    paddingBottom: "10px",
  },
  infoRow: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  infoRowVertical: {
    display: "flex",
    flexDirection: "column",
    marginBottom: "16px",
  },
  label: {
    fontSize: "13px",
    color: "#64748b",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  value: {
    fontSize: "15px",
    color: "#1e293b",
    fontWeight: "500",
  },
  textValue: {
    fontSize: "14px",
    color: "#475569",
    marginTop: "5px",
    lineHeight: "1.5",
    backgroundColor: "#f8fafc",
    padding: "10px",
    borderRadius: "6px",
  },
  inputGroup: {
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  select: {
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    fontSize: "15px",
    outlineColor: "#6366f1",
  },
  textarea: {
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    fontSize: "15px",
    minHeight: "120px",
    fontFamily: "inherit",
    resize: "vertical",
    outlineColor: "#6366f1",
  },
  saveButton: {
    width: "100%",
    padding: "14px",
    backgroundColor: "#6366f1",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  loading: {
    textAlign: "center",
    padding: "100px",
    fontSize: "18px",
    color: "#64748b",
  },
};

export default styles;
