const colors = {
  bg: "#ffffff",
  text: "#6b7280",
  textHover: "#111827",
  activeBg: "#f3f4f6",
  accent: "#3b82f6",
  border: "#e5e7eb",
};

const navbarStyles = {
  navbar: {
    height: "70px",
    width: "100%",
    backgroundColor: colors.bg,
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 110,
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: "220px",
    "@media (max-width: 1024px)": {
      minWidth: "auto",
    },
  },
  logoIcon: {
    fontSize: "24px",
    color: colors.accent,
  },
  logoTitle: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: colors.textHover,
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    "@media (max-width: 1100px)": {
      display: "none",
    },
  },
  contextNav: {
    display: "flex",
    gap: "4px",
    backgroundColor: "#f9fafb",
    padding: "4px",
    borderRadius: "10px",
    border: `1px solid ${colors.border}`,
    overflowX: "auto",
    maxWidth: "100%",
  },
  contextButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "transparent",
    color: colors.text,
    fontSize: "0.85rem",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
  },
  contextButtonActive: {
    backgroundColor: colors.bg,
    color: colors.accent,
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  contextButtonIcon: {
    fontSize: "14px",
  },
  rightSection: {
    minWidth: "220px",
    display: "flex",
    justifyContent: "flex-end",
    "@media (max-width: 1024px)": {
      display: "none",
    },
  },
  mobileContextSidebar: {
    position: "fixed",
    top: 0,
    right: 0,
    width: "280px",
    height: "100vh",
    backgroundColor: colors.bg,
    zIndex: 200,
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    boxShadow: "-4px 0 15px rgba(0,0,0,0.1)",
    transition: "transform 0.3s ease",
  },
  mobileBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    backdropFilter: "blur(2px)",
    zIndex: 199,
  },
};

export default navbarStyles;
