export const styles = {
  detailContainer: {
    padding: "100px 20px 40px 20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "30px",
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    background: "#f1f5f9",
    color: "#1e293b",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    minWidth: "120px",
  },
  detailTitle: {
    margin: "0",
    fontSize: "28px",
    color: "#1e293b",
    fontWeight: "700",
  },
  detailSubtitle: {
    margin: "8px 0 0 0",
    fontSize: "14px",
    color: "#64748b",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "15px",
    marginBottom: "30px",
  },
  statCard: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    display: "flex",
    alignItems: "center",
    gap: "15px",
    border: "1px solid #f1f5f9",
  },
  statIconContainer: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    background: "#f8fafc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
  },
  statContent: {
    display: "flex",
    flexDirection: "column",
  },
  statLabel: {
    fontSize: "12px",
    color: "#64748b",
    fontWeight: "500",
  },
  statValue: {
    fontSize: "18px",
    color: "#1e293b",
    fontWeight: "700",
  },
  tabsContainer: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    borderBottom: "2px solid #f1f5f9",
  },
  tabButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    background: "transparent",
    color: "#64748b",
    border: "none",
    borderBottom: "3px solid transparent",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  tabButtonActive: {
    color: "#3b82f6",
    borderBottomColor: "#3b82f6",
  },
  emailContentCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    overflow: "hidden",
    border: "1px solid #f1f5f9",
  },
  emailPreview: {
    padding: "20px",
    minHeight: "600px",
  },
  emailIframe: {
    width: "100%",
    height: "600px",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
  },
  noContent: {
    textAlign: "center",
    color: "#94a3b8",
    padding: "40px 20px",
    margin: "0",
  },
  recipientsCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    overflow: "hidden",
    border: "1px solid #f1f5f9",
  },
  filterSection: {
    padding: "15px 25px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
  },
  filterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "15px",
    alignItems: "flex-end",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  label: {
    fontSize: "11px",
    fontWeight: "600",
    color: "#64748b",
  },
  input: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
  },
  select: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
    background: "white",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "15px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "700",
    borderBottom: "2px solid #f1f5f9",
  },
  td: {
    padding: "15px",
    color: "#334155",
    fontSize: "13px",
    borderBottom: "1px solid #f1f5f9",
  },
  tdEmpty: {
    textAlign: "center",
    padding: "40px",
    color: "#94a3b8",
  },
  tr: {
    transition: "background 0.2s",
    "&:hover": { background: "#f8fafc" },
  },
  statusSuccess: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#ecfdf5",
    color: "#059669",
    fontSize: "11px",
    fontWeight: "700",
  },
  statusError: {
    padding: "3px 8px",
    borderRadius: "4px",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "11px",
    fontWeight: "700",
  },
  interactionCell: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  paginationContainer: {
    padding: "20px 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderTop: "1px solid #f1f5f9",
  },
  paginationInfo: {
    fontSize: "12px",
    color: "#64748b",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  pageButton: {
    padding: "6px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    background: "white",
    fontSize: "12px",
    cursor: "pointer",
  },
  pageInfo: {
    fontSize: "12px",
    color: "#1e293b",
    fontWeight: "700",
  },
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "100px 20px",
    minHeight: "500px",
    textAlign: "center",
  },
  detailLoading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "500px",
    padding: "100px 20px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "20px",
  },
};

export const spinnerStyles = `
  @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
`;

export const mergeStyles = (...objs) => Object.assign({}, ...objs);
