const styles = {
  loginContainer: {
    display: "flex",
    width: "100%",
    minHeight: "100vh",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    backgroundColor: "#f8fafc",
  },
  loginBranding: {
    flex: 1.3,
    background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    color: "#ffffff",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "60px",
    position: "relative",
    overflow: "hidden",
  },
  iconCircle: {
    width: "100px",
    height: "100px",
    background: "rgba(56, 189, 248, 0.1)",
    borderRadius: "30px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 30px",
    border: "1px solid rgba(56, 189, 248, 0.2)",
  },
  brandingIcon: {
    fontSize: "45px",
    color: "#38bdf8",
  },
  brandingH1: {
    fontSize: "2.8rem",
    fontWeight: "800",
    marginBottom: "20px",
    letterSpacing: "-1px",
  },
  brandingP: {
    fontSize: "1.2rem",
    lineHeight: "1.6",
    color: "#94a3b8",
    maxWidth: "380px",
    margin: "0 auto",
  },
  loginFormArea: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    backgroundColor: "#f8fafc",
  },
  loginForm: {
    width: "100%",
    maxWidth: "420px",
    padding: "40px",
    backgroundColor: "#ffffff",
    borderRadius: "24px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.08)",
    border: "1px solid #f1f5f9",
  },
  mobileHeader: {
    display: "none",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "30px",
  },
  mobileIcon: {
    fontSize: "40px",
    color: "#0f172a",
    marginBottom: "10px",
  },
  mobileTitle: {
    fontSize: "1.5rem",
    fontWeight: "800",
    color: "#0f172a",
    margin: 0,
  },
  textHeader: {
    textAlign: "center",
    marginBottom: "35px",
  },
  loginFormH2: {
    color: "#0f172a",
    fontSize: "1.75rem",
    fontWeight: "700",
    marginBottom: "10px",
  },
  formSubtitle: {
    color: "#64748b",
    fontSize: "0.95rem",
  },
  inputGroup: {
    marginBottom: "22px",
  },
  fieldLabel: {
    display: "block",
    fontSize: "0.85rem",
    fontWeight: "600",
    color: "#334155",
    marginBottom: "8px",
    marginLeft: "4px",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "#f8fafc",
    border: "1.5px solid #e2e8f0",
    borderRadius: "14px",
    transition: "all 0.2s ease",
  },
  inputWrapperFocus: {
    borderColor: "#0f172a",
    background: "#ffffff",
    boxShadow: "0 0 0 4px rgba(15, 23, 42, 0.05)",
  },
  inputIcon: {
    paddingLeft: "16px",
    color: "#94a3b8",
    fontSize: "1.1rem",
  },
  inputField: {
    width: "100%",
    padding: "14px 16px",
    border: "none",
    background: "transparent",
    fontSize: "1rem",
    outline: "none",
    color: "#1e293b",
  },
  passwordToggleIcon: {
    paddingRight: "16px",
    color: "#94a3b8",
    cursor: "pointer",
  },
  optionsRow: {
    display: "flex",
    alignItems: "center",
    marginBottom: "30px",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.9rem",
    color: "#475569",
    cursor: "pointer",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
    accentColor: "#0f172a",
  },
  loginButton: {
    width: "100%",
    padding: "16px",
    backgroundColor: "#0f172a",
    color: "#ffffff",
    border: "none",
    borderRadius: "14px",
    fontSize: "1rem",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 10px 15px -3px rgba(15, 23, 42, 0.2)",
  },
  errorMessage: {
    color: "#be123c",
    background: "#fff1f2",
    padding: "12px",
    borderRadius: "12px",
    marginBottom: "25px",
    fontSize: "0.85rem",
    textAlign: "center",
    border: "1px solid #ffe4e6",
    fontWeight: "500",
  },
  loadingOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    backdropFilter: "blur(4px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderRadius: "24px",
  },
  loadingText: {
    marginTop: "15px",
    color: "#0f172a",
    fontWeight: "600",
  },
};

export default styles;
